# Generated by Django 4.1.7 on 2023-02-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('pronunciation', models.CharField(max_length=100)),
                ('partOfSpeech', models.CharField(max_length=100)),
                ('definition', models.CharField(max_length=100)),
                ('context', models.CharField(max_length=100)),
            ],
        ),
    ]
